AG-7468 - Fix highlight mouse move outside viewport
ceolter/ag-grid pull request #5759
Opened 2022-11-08 16:27 UTC by alantreadway

https://ag-grid.atlassian.net/browse/AG-7468

Fixes series highlight remaining when pointer moves outside browser viewport.

Bonus:
- Attempts to consolidate all browser user-centric event handling into `InteractionManager`.
- Fixes touch support and merges into `InteractionManager`.

2022-11-08 16:51 UTC, alexanderby requested changes

2022-11-08 16:51 UTC, alexanderby commented on charts-packages/ag-charts-community/src/chart/chart.ts
> +        this.interactionManager.addListener('hover', (event) => this.onMouseMove(event));
"enter/exit" or "hover/leave"?

2022-11-08 16:51 UTC, alexanderby commented on charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +                offsetX,
Is there a need to expose these coordinates?

2022-11-08 16:51 UTC, alexanderby commented on charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +                offsetX = lastTouch?.clientX - rect.left;
Not sure, but if it is supposed to be used externally (not internally to determine some coordinate on chart), maybe using the offsetParent is the correct browser-like way? (it should take into account "position: absolute" etc)

2022-11-08 16:51 UTC, alexanderby commented on charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +            listeners?.forEach((listener: Listener<any>) => {
Here listeners have "?" (meaning it can be undefined), but a few lines later there is no "?".

2022-11-08 16:51 UTC, alexanderby commented on charts-packages/ag-charts-community/src/chart/navigator/navigator.ts
> +        interactionManager.addListener('exit', () => this.onDragStop());
When people start the drag, it can be annoying if the dragging is stopped as soon as you left a few pixels outside of chart. window.addEventListener should be used, so that even if the user's cursor went outside the window, he could keep navigating.

2022-11-09 09:29 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/chart.ts
> +        this.interactionManager.addListener('hover', (event) => this.onMouseMove(event));
:+1: I've changed `exit` to `leave` for better consistency.

2022-11-09 09:29 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +        switch (event.type) {
Adjusted to simplify the conditions here - thanks!

2022-11-09 09:29 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +                offsetX,
Yes - `offsetX` and `offsetY` are used to determine which shapes are being hovered over inside the `Canvas`. `pageX` and `pageY` are used to position the tooltip since it's rendered as a floating HTML element and needs to be positioned relative to the page itself.

2022-11-09 09:29 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +            listeners?.forEach((listener: Listener<any>) => {
Fixed.

2022-11-09 09:29 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/navigator/navigator.ts
> +        interactionManager.addListener('exit', () => this.onDragStop());
:+1: I've removed this case - however drag events aren't being received when the pointer is outside the viewport (but the drag resumes when the pointer re-enters the viewport - so that is an improvement).

2022-11-09 09:45 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +                offsetX = lastTouch?.clientX - rect.left;
I've done some testing (adding scrolling parent, different offsets) and the current code appears to behave correctly - it's also identical to the code being replaced, so at the moment I'm happy that we're at least not making things worse.

2022-11-09 11:12 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +                offsetX,
As discussed offline, these are only used internally in the chart code.

2022-11-09 11:12 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +                offsetX = lastTouch?.clientX - rect.left;
Plunker showing issues with `pageX` and `pageY`: https://plnkr.co/edit/MkJzSJmgSkPv4BXF?open=main.ts

Working on this now.

2022-11-09 17:15 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/interaction/interactionManager.ts
> +                offsetX = lastTouch?.clientX - rect.left;
Fixed 🤞

2022-11-09 17:15 UTC, alantreadway commented
@alexanderby PTAL, everything is now working.

2022-11-10 09:44 UTC, alexanderby commented on charts-packages/ag-charts-community/src/chart/chart.ts
> +        this.tooltip = new Tooltip(this.scene.canvas.element, document, document.body);
Maybe if we use "position: fixed", we can just put the element into the chart's wrapper?

2022-11-10 09:49 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/chart.ts
> +        this.tooltip = new Tooltip(this.scene.canvas.element, document, document.body);
Position is now fixed. We can't put it in the wrapper as the tooltip will get artificially clipped in some scenarios, it needs to be on `document.body`.

2022-11-10 09:51 UTC, alexanderby commented on charts-packages/ag-charts-community/src/chart/tooltip/tooltip.ts
> +        const naiveLeft = canvasRect.left + meta.offsetX - element.clientWidth / 2;
🤣 Naive!

2022-11-10 09:53 UTC, alexanderby commented on charts-packages/ag-charts-community/src/chart/tooltip/tooltip.ts
> +        this.constrained = left !== naiveLeft || top !== naiveTop;
Not sure if it tries to flip the tooltip. If so beware the arrow needs to be drawn in another place.

2022-11-10 09:55 UTC, alantreadway commented on charts-packages/ag-charts-community/src/chart/tooltip/tooltip.ts
> +        this.constrained = left !== naiveLeft || top !== naiveTop;
If `this.constrained` is `true` then the arrow is removed - so pretty much any adjustment to the tooltip position from the prior calculations removes it.

2022-11-10 09:56 UTC, alexanderby approved these changes

2022-11-10 09:58 UTC, merged